app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: hello world
  list:
    value: One,Two,Three


management:
  endpoints:
    web:
      exposure:
       include: "*"

spring:
  cloud:
    config:
      uri: http://localhost:8888
