my:
  greeting: hello world
  list:
    value: One,Two,Three

db:
  connection: test-connection-string-here
  host: 129.0.0.1
  port: 2400

management:
  endpoints:
    web:
      exposure:
        include: "*"